project_id = "lyjgjuhshxbfolloscyl"

[functions.generate-recipe]
verify_jwt = false

[functions.fetch-web-recipe]
verify_jwt = false

[functions.generate-newsletter-draft]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false
